# Generated by Django 5.0.1 on 2024-01-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_hex2',
            field=models.CharField(default='', max_length=64),
        ),
    ]
