# Generated by Django 5.0.1 on 2024-01-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_color_color_hex2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='remarks',
            field=models.CharField(max_length=1000),
        ),
    ]
